### ISSUE TITLE
branch: fsm - scooter_fsm build issue

### ISSUE THREAD

**Issue by PatrickCPE** [umlscooterteam/scooter#4]
patrick@patrick-desktop:~/ws/work/colcon_ws$ colcon build
[0.180s] WARNING:colcon.colcon_core.verb:Some selected packages are already built in one or more underlay workspaces:
	'cpp_pubsub' is in: /home/patrick/ws/work/colcon_ws/install/cpp_pubsub
	'more_interfaces' is in: /home/patrick/ws/work/colcon_ws/install/more_interfaces
	'my_package' is in: /home/patrick/ws/work/colcon_ws/install/my_package
	'my_package_c' is in: /home/patrick/ws/work/colcon_ws/install/my_package_c
	'py_pubsub' is in: /home/patrick/ws/work/colcon_ws/install/py_pubsub
	'py_srvcli' is in: /home/patrick/ws/work/colcon_ws/install/py_srvcli
	'python_action_server' is in: /home/patrick/ws/work/colcon_ws/install/python_action_server
	'python_parameters' is in: /home/patrick/ws/work/colcon_ws/install/python_parameters
	'scooter_core' is in: /home/patrick/ws/work/colcon_ws/install/scooter_core
	'turtlesim' is in: /home/patrick/ws/work/colcon_ws/install/turtlesim, /opt/ros/galactic
	'tutorial_interfaces' is in: /home/patrick/ws/work/colcon_ws/install/tutorial_interfaces
If a package in a merged underlay workspace is overridden and it installs headers, then all packages in the overlay must sort their include directories by workspace order. Failure to do so may result in build failures or undefined behavior at run time.
If the overridden package is used by another package in any underlay, then the overriding package in the overlay must be API and ABI compatible or undefined behavior at run time may occur.

If you understand the risks and want to override a package anyways, add the following to the command line:
	--allow-overriding cpp_pubsub more_interfaces my_package my_package_c py_pubsub py_srvcli python_action_server python_parameters scooter_core turtlesim tutorial_interfaces

This may be promoted to an error in a future release of colcon-core.
Starting >>> cpp_pubsub
Starting >>> more_interfaces
Starting >>> my_package
Starting >>> my_package_c
Starting >>> py_pubsub
Starting >>> py_srvcli
Starting >>> python_action_server
Starting >>> python_parameters
Starting >>> scooter_core
Starting >>> scooter_fsm
Starting >>> turtlesim
Starting >>> tutorial_interfaces
Finished <<< cpp_pubsub [1.52s]                                                                     
Finished <<< my_package_c [1.52s]
Finished <<< more_interfaces [1.58s]
Finished <<< tutorial_interfaces [1.59s]                                                        
Finished <<< turtlesim [1.70s]                                                                  
Finished <<< my_package [2.18s]                                                                 
Finished <<< py_pubsub [2.18s]
Finished <<< py_srvcli [2.19s]                                                         
--- stderr: scooter_fsm
error: can't copy 'resource/scooter_fsm': doesn't exist or not a regular file
---
Failed   <<< scooter_fsm [2.17s, exited with code 1]
Aborted  <<< python_action_server [2.19s]
Aborted  <<< scooter_core [2.18s]
Aborted  <<< python_parameters [2.19s]

Summary: 8 packages finished [2.34s]
  1 package failed: scooter_fsm
  3 packages aborted: python_action_server python_parameters scooter_core
  1 package had stderr output: scooter_fsm

**Comment by sashaiw** [comment]
Hopefully fixed in commit 7f6e3d7
